# Generated by Django 4.0.4 on 2022-05-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'post',
            },
        ),
    ]
